version: '3.8'

networks:
  data-quality-network:
    driver: bridge

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - data-quality-network

  kafka:
    build:
      context: .
      dockerfile: dockerfiles/kafka.Dockerfile
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - data-quality-network
    volumes:
      - ./experiments-configurations.yaml:/config/experiments.yaml
    env_file:
      - .env

  stream:
    build:
      context: .
      dockerfile: dockerfiles/stream.Dockerfile
    container_name: stream
    depends_on:
      - kafka
    networks:
      - data-quality-network
    environment:
      - INPUT_TOPIC=${INPUT_TOPIC}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - WINDOW_DURATION=${WINDOW_DURATION}
      - MESSAGES_PER_WINDOW=${MESSAGES_PER_WINDOW}
    env_file:
      - .env

  deequ:
    build:
      context: .
      dockerfile: dockerfiles/deequ.Dockerfile
    container_name: deequ
    depends_on:
      - kafka
    networks:
      - data-quality-network
    environment:
      - SPARK_MASTER=${SPARK_MASTER}
      - SPARK_NUM_CORES=${SPARK_NUM_CORES}
    env_file:
      - .env
    volumes:
      - ./execution-results/deequ:/app/executionData

  daq:
    build:
      context: .
      dockerfile: dockerfiles/daq.Dockerfile
    container_name: daq
    depends_on:
      - kafka
    networks:
      - data-quality-network
    environment:
      - INPUT_TOPIC=${INPUT_TOPIC}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    env_file:
      - .env
    volumes:
      - ./execution-results/stream-daq:/app/data
