# kafka configurations
kafka_topic: test_topic
kafka_server: 'localhost:9092' # change to '<container_name>:9092' if using docker

# stream configurations
number_of_elements_to_send: 1e4
chance_of_missing_value: 0.1
sleep_seconds_between_messages: 1e-10
min_stream_value: 0
max_stream_value: 100

# data quality checks configurations
low_threshold: 10 # values smaller (excluded) than this threshold will be considered invalid
high_threshold: 90 # values greater (excluded) than this threshold will be considered inaccurate

# results sink configuration
directory_base_name: './results/' # the parent directory to store all execution results
pathway_directory: 'pathway/' # the directory inside parent to store pathway-specific results
faust_directory: 'faust/' # the directory inside parent to store faust-specific results
bytewax_directory: 'bytewax/' # the directory inside parent to store bytewax-specific results
quix_directory: 'quix/' # the directory inside parent to store quix-specific results
missing_values_file_name: 'missing_values.csv' # the file name inside parent and framework-specific directories for missing values
out_of_range_values_file_name: 'out_of_range_values.csv' # the file name inside parent and framework-specific directories for out of range values
results_file_name: 'missing_out_of_range_values.csv' # used only if both metrics are written to the same file (Faust)
